In [5]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10):my_arr2=my_arr * 2

%time for _ in range(10):my_list2=[x*2 for x in my_list]

CPU times: user 12 ms, sys: 0 ns, total: 12 ms
Wall time: 12 ms


CPU times: user 424 ms, sys: 104 ms, total: 527 ms
Wall time: 528 ms


In [1]:
import numpy as np

data=np.random.randn(2,3)
print(data)

[[ 0.10043798  0.08816612 -0.00988228]
 [-0.21871793 -1.62142438  0.67446083]]


In [2]:
print('data * 10 : \n',data*10)

data * 10 : 
 [[  1.00437979   0.88166115  -0.09882283]
 [ -2.18717925 -16.21424375   6.74460831]]


In [3]:
print(data+data)

[[ 0.20087596  0.17633223 -0.01976457]
 [-0.43743585 -3.24284875  1.34892166]]


In [4]:
data.dtype
data.shape

(2, 3)

In [5]:
print(data.dtype)
print(data.shape)

float64
(2, 3)


In [6]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)


[6.  7.5 8.  0.  1. ]


In [7]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2)

In [8]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

2
(2, 4)
int64


In [10]:
print(arr1.dtype)
print(arr2.dtype)

float64
int64


In [11]:
print(np.zeros(10))
print(np.zeros((4,2,3)))
print(np.empty((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[[[4.67834745e-310 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]]


In [12]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [13]:
print(np.full((2,4)))

TypeError: full() missing 1 required positional argument: 'fill_value'

In [14]:
print(np.full((2, 4), 4))


[[4 4 4 4]
 [4 4 4 4]]


In [15]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
print(np.eye(6, dtype=int))


[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [19]:
arr = np.array([1, 2, 3, 4, 5])
float_arr = arr.astype(np.float64)
print(arr)
print(float_arr)


[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [20]:
fl_arr=[1.2,3.4,5.6,7.8]
print(np.array(fl_arr))
print(np.array(fl_arr).astype(np.int32))

[1.2 3.4 5.6 7.8]
[1 3 5 7]


In [22]:
numeric_strings = np.array(['1.2', '3.4', '5.6'], dtype=np.string_)
print(numeric_strings)
print(numeric_strings.astype(np.float64))


[b'1.2' b'3.4' b'5.6']
[1.2 3.4 5.6]
