In [5]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10):my_arr2=my_arr * 2

%time for _ in range(10):my_list2=[x*2 for x in my_list]

CPU times: user 12 ms, sys: 0 ns, total: 12 ms
Wall time: 12 ms


CPU times: user 424 ms, sys: 104 ms, total: 527 ms
Wall time: 528 ms


In [1]:
import numpy as np

data=np.random.randn(2,3)
print(data)

[[ 0.10043798  0.08816612 -0.00988228]
 [-0.21871793 -1.62142438  0.67446083]]


In [2]:
print('data * 10 : \n',data*10)

data * 10 : 
 [[  1.00437979   0.88166115  -0.09882283]
 [ -2.18717925 -16.21424375   6.74460831]]


In [3]:
print(data+data)

[[ 0.20087596  0.17633223 -0.01976457]
 [-0.43743585 -3.24284875  1.34892166]]


In [4]:
data.dtype
data.shape

(2, 3)

In [5]:
print(data.dtype)
print(data.shape)

float64
(2, 3)


In [6]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)


[6.  7.5 8.  0.  1. ]


In [7]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2)

In [8]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

2
(2, 4)
int64


In [10]:
print(arr1.dtype)
print(arr2.dtype)

float64
int64


In [11]:
print(np.zeros(10))
print(np.zeros((4,2,3)))
print(np.empty((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[[[4.67834745e-310 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]]


In [12]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [13]:
print(np.full((2,4)))

TypeError: full() missing 1 required positional argument: 'fill_value'

In [14]:
print(np.full((2, 4), 4))


[[4 4 4 4]
 [4 4 4 4]]


In [15]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
print(np.eye(6, dtype=int))


[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [19]:
arr = np.array([1, 2, 3, 4, 5])
float_arr = arr.astype(np.float64)
print(arr)
print(float_arr)


[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [20]:
fl_arr=[1.2,3.4,5.6,7.8]
print(np.array(fl_arr))
print(np.array(fl_arr).astype(np.int32))

[1.2 3.4 5.6 7.8]
[1 3 5 7]


In [22]:
numeric_strings = np.array(['1.2', '3.4', '5.6'], dtype=np.string_)
print(numeric_strings)
print(numeric_strings.astype(np.float64))


[b'1.2' b'3.4' b'5.6']
[1.2 3.4 5.6]


In [23]:
arr3=np.array([[0.4,.6,.9,2.3],[2.1,0.5,0.1,5.2]])
print(arr3)
print(arr2)
print(arr3>arr2)

[[0.4 0.6 0.9 2.3]
 [2.1 0.5 0.1 5.2]]
[[False False False False]
 [False False False False]]


In [24]:
arr3=np.array([[0.4,.6,.9,2.3],[2.1,0.5,0.1,5.2]])
print(arr3)
print(arr2)
print(arr3>arr2)

[[0.4 0.6 0.9 2.3]
 [2.1 0.5 0.1 5.2]]
[[1 2 3 4]
 [5 6 7 8]]
[[False False False False]
 [False False False False]]


In [25]:
# 广播机制

a=np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b=np.array([1.0,2.0,3.0,4.0])
print(a)
print(b)
print(np.broadcast(a,b))

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
[1. 2. 3. 4.]


ValueError: shape mismatch: objects cannot be broadcast to a single shape

In [26]:
a=np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b=np.array([1.0,2.0,3.0,4.0])
print(a)
print(b)
print(a+b)

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
[1. 2. 3. 4.]


ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [27]:
a=np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b=np.array([1.0,2.0,3.0])
print(a)
print(b)
print(np.broadcast(a,b))

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
[1. 2. 3.]


In [30]:
a=np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b=np.array([1.0,2.0,3.0],[1.0,1.0,1.0])
print(a)
print('================')
print(b)
print('================')
print(a+b)

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
[1. 2. 3.]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [31]:
a=np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b=np.array([1.0,2.0,3.0],[1.0,1.0,1.0])
print(a)
print('================')
print(b)
print('================')
print(a+b)

TypeError: data type not understood

In [32]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [33]:
print(arr3d[0].shape())

TypeError: 'tuple' object is not callable

In [34]:
print(arr3d[0])

[[1 2 3]
 [4 5 6]]


In [35]:
print(arr3d[1,0])

[7 8 9]


In [36]:
print(arr3d[1][0])

[7 8 9]


In [37]:
arr3d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(arr3d[2][0:2])

[7, 8]


In [39]:
print(arr3d[:2, 1:])


TypeError: list indices must be integers or slices, not tuple

In [40]:
print(np.array(arr3d)[:2, :2])


[[1 2]
 [4 5]]


In [41]:
print(arr3d[:, :1])


TypeError: list indices must be integers or slices, not tuple

In [42]:
print(np.array(arr3d)[:,:1])

[[1]
 [4]
 [7]]


In [43]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

print(names)
print(data)


['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.77947549 -1.85411955 -0.42801381 -0.27139697]
 [ 0.56273155 -0.1305178  -1.18396706  0.18883149]
 [ 0.65948948  0.42761761 -0.25882518  0.44485872]
 [ 0.0462582  -0.13474608 -0.86043574 -0.64459813]
 [ 1.468602    0.80095064  1.14806067  0.12863918]
 [ 0.09403273 -0.64534257 -0.35495909 -0.76128038]
 [-2.29814436  0.22697471  1.04934407 -1.05089755]]


In [44]:
print(names == 'Bob')


[ True False False  True False False False]


In [45]:
print(data[names == 'Bob'])


[[ 0.77947549 -1.85411955 -0.42801381 -0.27139697]
 [ 0.0462582  -0.13474608 -0.86043574 -0.64459813]]


In [46]:
print(data[[True, True, False, False, False, False, True]])


[]


In [47]:
print(data[[True, True, False, False, False, False, True]])


[[ 0.77947549 -1.85411955 -0.42801381 -0.27139697]
 [ 0.56273155 -0.1305178  -1.18396706  0.18883149]
 [-2.29814436  0.22697471  1.04934407 -1.05089755]]


In [48]:
print(data[[True, True, False, False, False, False, True], 2:])


[[-0.42801381 -0.27139697]
 [-1.18396706  0.18883149]
 [ 1.04934407 -1.05089755]]


In [49]:
print(data[~[True, True, False, False, False, False, True]])


TypeError: bad operand type for unary ~: 'list'

In [50]:
print(data[~(names == 'Bob')])


[[ 0.56273155 -0.1305178  -1.18396706  0.18883149]
 [ 0.65948948  0.42761761 -0.25882518  0.44485872]
 [ 1.468602    0.80095064  1.14806067  0.12863918]
 [ 0.09403273 -0.64534257 -0.35495909 -0.76128038]
 [-2.29814436  0.22697471  1.04934407 -1.05089755]]


In [51]:
data[data <= 0] = 0
print(data)


[[0.77947549 0.         0.         0.        ]
 [0.56273155 0.         0.         0.18883149]
 [0.65948948 0.42761761 0.         0.44485872]
 [0.0462582  0.         0.         0.        ]
 [1.468602   0.80095064 1.14806067 0.12863918]
 [0.09403273 0.         0.         0.        ]
 [0.         0.22697471 1.04934407 0.        ]]


In [52]:
data *= 10


In [53]:
print(data)

[[ 7.79475486  0.          0.          0.        ]
 [ 5.62731546  0.          0.          1.88831491]
 [ 6.59489485  4.27617613  0.          4.44858719]
 [ 0.46258196  0.          0.          0.        ]
 [14.68602002  8.00950635 11.48060672  1.28639184]
 [ 0.94032726  0.          0.          0.        ]
 [ 0.          2.26974709 10.49344067  0.        ]]


In [54]:
print(data.astype(np.int32))

[[ 7  0  0  0]
 [ 5  0  0  1]
 [ 6  4  0  4]
 [ 0  0  0  0]
 [14  8 11  1]
 [ 0  0  0  0]
 [ 0  2 10  0]]


In [55]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
print(arr)


[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [56]:
print(arr[[3, 5, 2, 7]])


[[3. 3. 3. 3.]
 [5. 5. 5. 5.]
 [2. 2. 2. 2.]
 [7. 7. 7. 7.]]


In [58]:
arr = np.arange(32).reshape((8, 4))
print(arr)
print('====================')
print(arr[[1, 2, 3, 5], [0, 2, 1, 3]])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 4 10 13 23]


In [59]:
print(arr[[1, 2, 3, 5]][:, [0, 2, 1, 3]])


[[ 4  6  5  7]
 [ 8 10  9 11]
 [12 14 13 15]
 [20 22 21 23]]


In [60]:
print(arr[[1, 2, 3, 5]][:, [0, 2, 1, 3]].T)

[[ 4  8 12 20]
 [ 6 10 14 22]
 [ 5  9 13 21]
 [ 7 11 15 23]]


In [61]:
E = np.identity(3)
A = np.arange(9).reshape((3, 3))
print('E:', E)
print('=' * 20)
print('A:', A)
print('=' * 20)
print(np.dot(E, A))


E: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A: [[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [63]:
print(np.dot(A.T, A))
print('='*10)
print(np.dot(A, A.T))


[[45 54 63]
 [54 66 78]
 [63 78 93]]
[[  5  14  23]
 [ 14  50  86]
 [ 23  86 149]]


In [65]:
B = np.arange(5).reshape((1, 5))
print(np.dot(B, B.T))
print('=' * 10)
print(np.dot(B.T, B))


[[30]]
[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]


In [66]:
arr = np.arange(16).reshape((2, 2, 4))
print(arr)
print('=' * 10)
print(arr.transpose((1, 0, 2)))


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [67]:
print(arr.transpose([0, 2, 1]))


[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [68]:
print(arr.transpose([2, 0, 1]))


[[[ 0  4]
  [ 8 12]]

 [[ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]]

 [[ 3  7]
  [11 15]]]


In [71]:
print(arr.copy().T)
print('=' * 20)
print(arr.swapaxes(0, 2))


[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]
[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]
