In [1]:
import numpy as np

x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

print(x)
print(10*'=')
print(y)
print(10*'=')
print(x.dot(y))
print(10*'=')
print(y.dot(x))

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
[[ 28.  64.]
 [ 67. 181.]]
[[ 98. 127. 156.]
 [ 27.  33.  39.]
 [ 44.  61.  78.]]


In [2]:
print(np.ones(3))
print(10 * '=')
print(np.dot(x, np.ones(3)))
print(10 * '=')
print(np.dot(np.ones(3), x))


[1. 1. 1.]
[ 6. 15.]


ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

In [3]:
print(np.dot(np.ones(3), x.T))


[ 6. 15.]


In [4]:
print(x @ np.ones(3))

[ 6. 15.]


In [5]:
from numpy.linalg import inv, qr

X = np.random.randn(5, 5)
mat = X.T.dot(X)
print(inv(mat))
print(10 * '=')
print(mat.dot(inv(mat)))

q, r = qr(mat)
print(r)


[[  1.24462722   0.41045958  -0.02096639   1.51702344  -0.59195333]
 [  0.41045958   0.4667729    1.48853352  -1.09554057   0.89167861]
 [ -0.02096639   1.48853352  11.6627005  -12.97151258   9.27057052]
 [  1.51702344  -1.09554057 -12.97151258  16.89363613 -11.52978119]
 [ -0.59195333   0.89167861   9.27057052 -11.52978119   8.19235913]]
[[ 1.00000000e+00  1.23023603e-15 -5.61956988e-15 -4.31360326e-15
   1.92588422e-15]
 [ 1.89851990e-16  1.00000000e+00  2.51460736e-15 -4.17630799e-16
   4.35474905e-15]
 [ 9.72231756e-17 -2.14033875e-16  1.00000000e+00  2.06331770e-15
  -4.33058739e-15]
 [ 5.95526647e-16 -1.48434252e-15 -1.34850265e-14  1.00000000e+00
  -1.69227431e-14]
 [-7.42494449e-16 -2.69137521e-16  3.39137061e-15  8.33410791e-16
   1.00000000e+00]]
[[-9.64470871  6.93600194  1.55114613  9.82630524 10.67946819]
 [ 0.         -7.22831878  3.14976288  1.85905408 -0.15744903]
 [ 0.          0.         -1.30857771  1.57060545  3.77663063]
 [ 0.          0.          0.         -1.146

In [1]:
from numpy.linalg import inv, qr
import numpy as np

X = np.random.randn(5, 5)
mat = X.T.dot(X)
print(inv(mat))
print(10 * '=')
print(mat.dot(inv(mat)))

q, r = qr(mat)
print(r)


[[ 1.29162951 -0.97237152 -0.3398688   0.92437901  0.27609522]
 [-0.97237152  0.97191151  0.55268202 -0.72359832 -0.15811589]
 [-0.3398688   0.55268202  0.95949089 -0.07553207  0.09912279]
 [ 0.92437901 -0.72359832 -0.07553207  0.98187297  0.18694212]
 [ 0.27609522 -0.15811589  0.09912279  0.18694212  0.31011706]]
[[ 1.00000000e+00 -1.28674783e-16  1.09802329e-17  1.15220460e-16
  -1.06531231e-16]
 [ 2.12911131e-15  1.00000000e+00 -2.32340003e-16  1.40392052e-15
  -9.69628447e-17]
 [-5.22792896e-16 -6.23109722e-16  1.00000000e+00 -4.83124695e-16
   1.75729321e-17]
 [ 8.51545105e-17  1.26186583e-16  3.11974498e-16  1.00000000e+00
  -1.50008493e-16]
 [ 5.16390925e-16 -1.86551275e-16  1.02086004e-16  8.04186000e-17
   1.00000000e+00]]
[[-6.58235511 -6.76998737  1.51629522  1.24945192  1.87899557]
 [ 0.         -8.39967507  5.17717136 -5.70594605 -3.42519139]
 [ 0.          0.         -1.0992931  -0.83753505  1.77226239]
 [ 0.          0.          0.         -1.06719966  2.66021345]
 [ 0. 

In [2]:
arr = np.array([1, 2, 3, 4])
print(np.diag(arr))


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [3]:
print(np.diag(np.diag(arr)))

[1 2 3 4]


In [4]:
print(np.trace(np.diag(arr)))

10


In [5]:
print(np.det(np.diag(arr)))

AttributeError: module 'numpy' has no attribute 'det'

In [6]:
import numpy.linalg as lg
print(lg.det(np.diag(arr)))

23.999999999999993


In [7]:
print(int(lg.det(np.diag(arr))))

23


In [8]:
import math

print(math.ceil(int(lg.det(np.diag(arr)))))

23
