In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
print(10*'=')
print(np.sqrt(arr))
print(10*'=')
print(np.exp(arr))


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [3]:
x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(10 * '=')
print(y)
print(10 * '=')
print(np.maximum(x, y))
print(10 * '=')
print(np.add(x, y))


[ 1.38129563  0.20695289 -0.72002074  0.30942986 -1.78958795 -0.65612325
 -0.11212387 -0.87555803]
[-0.16745332 -0.53212308 -1.80146662 -0.26755979  0.23853116  0.52770828
 -0.30958192  0.73030955]
[ 1.38129563  0.20695289 -0.72002074  0.30942986  0.23853116  0.52770828
 -0.11212387  0.73030955]
[ 1.2138423  -0.32517019 -2.52148736  0.04187008 -1.55105679 -0.12841497
 -0.42170579 -0.14524848]


In [4]:
arr = np.random.randn(7) * 5
print(arr)
print(10 * '=')
remainder, whole_part = np.modf(arr)
print(remainder)
print(10 * '=')
print(whole_part)


[-2.21578411 -2.25723458  0.67069306  3.49679491  1.53356331 14.41398207
 -4.05650513]
[-0.21578411 -0.25723458  0.67069306  0.49679491  0.53356331  0.41398207
 -0.05650513]
[-2. -2.  0.  3.  1. 14. -4.]


In [5]:
print(arr)
print(10 * '=')
print(np.sqrt(arr))
print(10 * '=')
print(np.sqrt(arr, arr))
print(arr)


[-2.21578411 -2.25723458  0.67069306  3.49679491  1.53356331 14.41398207
 -4.05650513]
[       nan        nan 0.81895852 1.8699719  1.23837123 3.79657504
        nan]
[       nan        nan 0.81895852 1.8699719  1.23837123 3.79657504
        nan]
[       nan        nan 0.81895852 1.8699719  1.23837123 3.79657504
        nan]


/home/steve/.local/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until
/home/steve/.local/lib/python3.6/site-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in sqrt
  """


In [6]:
arr = np.arange(10)
print(arr)
print(10 * '=')
print(np.fabs(arr, arr))
print(10 * '=')
print(arr)


[0 1 2 3 4 5 6 7 8 9]


TypeError: ufunc 'fabs' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''

In [7]:
arr = np.arange(10)
print(arr)
print(10 * '=')
print(np.fabs(arr))
print(10 * '=')
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


In [8]:
arr = np.arange(10)
print(np.sign(arr))


[0 1 1 1 1 1 1 1 1 1]


In [9]:
arr = np.arange(10)
print(arr)
print(10 * '=')
print(np.sign(arr))


[0 1 2 3 4 5 6 7 8 9]
[0 1 1 1 1 1 1 1 1 1]


In [10]:
arr = np.random.randn(10)
print(arr)
print(10 * '=')
print(np.sign(arr))


[-0.79081863  1.20163712  2.24082022 -1.30426587 -0.61436966  1.07702234
 -1.0611261   0.30811194 -1.24382029  0.30016644]
[-1.  1.  1. -1. -1.  1. -1.  1. -1.  1.]


In [11]:
arr = np.random.randn(10) * 10
print(arr)
print(10 * '=')
print(np.ceil(arr))
print(10 * '=')
print(np.floor(arr))


[ -5.22130601   0.07617485  -0.85595658  -5.7632768   23.8556817
  -6.77176485 -14.4452011   12.9546558   10.52142349   5.20234623]
[ -5.   1.  -0.  -5.  24.  -6. -14.  13.  11.   6.]
[ -6.   0.  -1.  -6.  23.  -7. -15.  12.  10.   5.]
