In [1]:
import numpy as np

np.random.randn()

1.4626302079596414

In [3]:
2.5*np.random.randn(2,4)+3

array([[-1.71398334,  3.63489198,  4.94457013,  1.69090313],
       [ 6.42733577,  3.38945367,  3.53489577,  2.7566044 ]])

In [4]:
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
print(xv)


[[0.  0.5 1. ]
 [0.  0.5 1. ]]


In [5]:
yv

array([[0., 0., 0.],
       [1., 1., 1.]])

In [6]:
xv, yv = np.meshgrid(x, y, sparse=True)
xv
yv


array([[0.],
       [1.]])

In [7]:
xv, yv = np.meshgrid(x, y, sparse=True)
xv

array([[0. , 0.5, 1. ]])

In [8]:
import matplotlib.pyplot as plt

x = np.arange(-5, 5, .01)
y = np.arange(-5, 5, .01)

xx, yy = np.meshgrid(x, y, sparse=True)
z = np.sin(xx ** 2 + yy ** 2) / (xx ** 2 + yy ** 2)
h = plt.contourf(x, y, z)


In [1]:
a = np.array([[2, 7, 4, 2],
              [35, 9, 1, 5],
              [22, 12, 3, 2]])
print(a[np.lexsort(a.T)])
print(10*'=')
print(a[np.lexsort(-a.T)])



NameError: name 'np' is not defined

In [2]:
import numpy as np

a = np.array([[2, 7, 4, 2],
              [35, 9, 1, 5],
              [22, 12, 3, 2]])
print(a[np.lexsort(a.T)])
print(10*'=')
print(a[np.lexsort(-a.T)])




[[22 12  3  2]
 [ 2  7  4  2]
 [35  9  1  5]]
[[35  9  1  5]
 [ 2  7  4  2]
 [22 12  3  2]]
