In [1]:
import numpy as np

arr = np.arange(10)
np.save('some_array', arr)


In [2]:
print(np.load('some_array.npy'))

[0 1 2 3 4 5 6 7 8 9]


In [3]:
np.savez('array_archive.npz', a=arr, b=arr)

arch = np.load('array_archive.npz')
print(arch['a'])


[0 1 2 3 4 5 6 7 8 9]


In [4]:
np.savez_compressed('array_compressed.npz', a=arr, b=arr)

print(np.load('array_compressed.npz')['a'])


[0 1 2 3 4 5 6 7 8 9]
